### PR TITLE
abc-408 addition URL parameters for filters

### PR DESCRIPTION
**Pull request by Mil-m**

### CODE REVIEW

**Comment by Raheelaaslam1024** [comment]
@Mil-m can you please remove the conflict.

**Comment by Raheelaaslam1024** [comment]
@Mil-m Please look into this PR is not working.

**Comment by Mil-m** [comment]
> @Mil-m Please look into this PR is not working.

@Raheelaaslam1024 I finally fixed it with the changing previous logic here
could take a look again, please

**Comment by Raheelaaslam1024** [comment]
@Mil-m I checked you PR on local its still have issues if you filter data it give you empty response and actually we have data for the same filters.

Screenshot 2024-12-05 at 13 39 46

On prod:

Screenshot 2024-12-05 at 13 46 28

**Comment by Mil-m** [comment]
> @Mil-m I checked this PR on local its still have issues if you filter data it give empty response and actually we have data for the same filters.
> 
> Screenshot 2024-12-05 at 13 39 46
> On prod:
> 
> Screenshot 2024-12-05 at 13 46 28

@Raheelaaslam1024 but I see 166 records in my branch for these filters

Screenshot 2024-12-05 at 23 25 00

**Comment by yroochun** [comment]
As discussed today on huddle, several issues were identified in this PR. The phylogeny query parameters are not being added to the URL as expected, and when a URL containing these parameters is copied to another tab, the correct search results are not displayed

**Pull request closed without merging**
