### PR TITLE
abc-411 add scrolling to project names filters

### PR DESCRIPTION
**Pull request by Mil-m**

### CODE REVIEW

**Comment by Raheelaaslam1024** [comment]
@Mil-m I tested branch it working in happy scenario but if i select this project name collapse and expand button stop working and in console this is the error.
Screenshot 2024-12-04 at 10 49 48

**Comment by Mil-m** [comment]
> @Mil-m I tested branch it working in happy scenario but if i select this project name collapse and expand button stop working and in console this is the error. Screenshot 2024-12-04 at 10 49 48

but if we switched to the main branch we will have only 5 values for this filter
so it shouldn't be a bug isn't it?

Screenshot 2024-12-05 at 00 40 04

**Comment by Raheelaaslam1024** [comment]
@Mil-m are you available for call ?I showed you error on call if you want we can regenerate the same error on call again.

**Comment by Mil-m** [comment]
> @Mil-m are you available for call ?I showed you error on call if you want we can regenerate the same error on call again.

@Raheelaaslam1024 do you still receive any errors?

**Comment by Alexey-ebi** [comment]
@Raheelaaslam1024 is on leave today, @yroochun can you review this PR and merge it once it's ready please

**Comment by yroochun** [comment]
There are still issues with the '+' and '-' when selecting entries. The expand and contract icons are not updated according to the selection made

**Pull request merged**
